/*
 * This file is generated by jOOQ.
 */
package com.zaytsevp.pethousesjooq.model;


import com.zaytsevp.pethousesjooq.model.tables.House;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HOUSE_PKEY = Indexes0.HOUSE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index HOUSE_PKEY = Internal.createIndex("house_pkey", House.HOUSE, new OrderField[] { House.HOUSE.ID }, true);
    }
}
