/*
 * This file is generated by jOOQ.
 */
package com.zaytsevp.pethousesjooq.model;


import com.zaytsevp.pethousesjooq.model.tables.House;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.house</code>.
     */
    public static final House HOUSE = com.zaytsevp.pethousesjooq.model.tables.House.HOUSE;
}
